kind: Pod
apiVersion: v1
metadata:
  name: secret-file-pod
  labels:
    name: secret-file-pod
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: file-secret
  containers:
  - name: ssh-test-container
    image: busybox
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/etc/secret-volume"