apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: secret-env-container
    image: redis
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: simple-secret
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: simple-secret
            key: password
      - name: NON_SECRET
        value: "it doesn't even matter"
  restartPolicy: Never