apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: task-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
