apiVersion: v1
kind: Secret
metadata:
  name: app-env-secret
type: Opaque
data:
  DB_HOST: ZmFrZQ==
  DB_NAME: ZmFrZQ==
  DB_PASSWORD: ZmFrZQ==
  DB_USERNAME: ZmFrZQ==
  FIREBASE_SERVER_KEY: ZmFrZXM=
  JWT_SECRET: ZmFrZQ==
  MAP_API_KEY: ZmFrZQ==
  PHTOTO_EDITOR_SIGNATURE: ZmFrZQ==
  PUSH_NOTIFICATION_APP: cHVzaF9ub3RpZmljYXRpb25fYXBw
  REDIS_PASS: ZmFrZQ==
  REDIS_URL: cmVkaXM6Ly86cGFzc0B1cmw6cG9ydA==
  SECRET_KEY: ZmFrZQ==
  SMTP_PASSWORD: ZmFrZQ==
