{{- if .Values.externalRegistry.enabled }}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Files.Get "config/registry-config.json" | b64enc }}
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
{{- end}}